/*
  Board v2 apply script for an existing hybrid DB.

  Use this when Hibernate already created BOARDS / STOCKS / POSTS.BOARD_ID
  but the old POSTS.USERNAME, POSTS.SYMBOL, COMMENTS.USERNAME columns still exist.
*/

MERGE INTO MARKETS m
USING (
    SELECT 'KR' MARKET_CODE, 'Korea Stock Market' MARKET_NAME, 'KOR' COUNTRY, 'KRW' CURRENCY FROM DUAL
    UNION ALL
    SELECT 'US', 'United States Stock Market', 'USA', 'USD' FROM DUAL
) src
ON (m.MARKET_CODE = src.MARKET_CODE)
WHEN NOT MATCHED THEN
    INSERT (MARKET_CODE, MARKET_NAME, COUNTRY, CURRENCY)
    VALUES (src.MARKET_CODE, src.MARKET_NAME, src.COUNTRY, src.CURRENCY);

INSERT INTO BOARDS (
    BOARD_SLUG,
    BOARD_NAME,
    BOARD_DESCRIPTION,
    BOARD_TYPE,
    MARKET_CODE,
    STOCK_ID,
    WRITE_ROLE,
    HIDDEN,
    SORT_ORDER,
    CREATED_AT
)
SELECT 'free', '자유게시판', '시장과 무관한 자유 주제 게시판', 'GENERAL', NULL, NULL, 'USER', 0, 10, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOARDS WHERE BOARD_SLUG = 'free');

INSERT INTO BOARDS (
    BOARD_SLUG,
    BOARD_NAME,
    BOARD_DESCRIPTION,
    BOARD_TYPE,
    MARKET_CODE,
    STOCK_ID,
    WRITE_ROLE,
    HIDDEN,
    SORT_ORDER,
    CREATED_AT
)
SELECT 'notice', '공지사항', '서비스 공지 게시판', 'NOTICE', NULL, NULL, 'ADMIN', 0, 0, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOARDS WHERE BOARD_SLUG = 'notice');

INSERT INTO BOARDS (
    BOARD_SLUG,
    BOARD_NAME,
    BOARD_DESCRIPTION,
    BOARD_TYPE,
    MARKET_CODE,
    STOCK_ID,
    WRITE_ROLE,
    HIDDEN,
    SORT_ORDER,
    CREATED_AT
)
SELECT 'markets/KR', '한국 주식 게시판', '한국 주식 전체 게시판', 'MARKET', 'KR', NULL, 'USER', 0, 20, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOARDS WHERE BOARD_SLUG = 'markets/KR');

INSERT INTO BOARDS (
    BOARD_SLUG,
    BOARD_NAME,
    BOARD_DESCRIPTION,
    BOARD_TYPE,
    MARKET_CODE,
    STOCK_ID,
    WRITE_ROLE,
    HIDDEN,
    SORT_ORDER,
    CREATED_AT
)
SELECT 'markets/US', '미국 주식 게시판', '미국 주식 전체 게시판', 'MARKET', 'US', NULL, 'USER', 0, 30, SYSTIMESTAMP
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM BOARDS WHERE BOARD_SLUG = 'markets/US');

MERGE INTO STOCKS st
USING (
    SELECT DISTINCT MARKET_CODE, SYMBOL, STOCK_NAME
    FROM (
        SELECT MARKET_CODE, UPPER(SYMBOL) SYMBOL, STOCK_NAME
        FROM HOLDINGS
        WHERE SYMBOL IS NOT NULL

        UNION ALL

        SELECT MARKET_CODE, UPPER(SYMBOL) SYMBOL, STOCK_NAME
        FROM TRADE_ORDERS
        WHERE SYMBOL IS NOT NULL

        UNION ALL

        SELECT
            CASE
                WHEN REGEXP_LIKE(SYMBOL, '^[0-9]{6}$') THEN 'KRX'
                ELSE 'NASDAQ'
            END MARKET_CODE,
            UPPER(SYMBOL) SYMBOL,
            UPPER(SYMBOL) STOCK_NAME
        FROM POSTS
        WHERE SYMBOL IS NOT NULL
    )
) src
ON (st.MARKET_CODE = src.MARKET_CODE AND st.SYMBOL = src.SYMBOL)
WHEN NOT MATCHED THEN
    INSERT (MARKET_CODE, SYMBOL, STOCK_NAME, LISTED, CREATED_AT)
    VALUES (src.MARKET_CODE, src.SYMBOL, src.STOCK_NAME, 1, SYSTIMESTAMP);

INSERT INTO BOARDS (
    BOARD_SLUG,
    BOARD_NAME,
    BOARD_DESCRIPTION,
    BOARD_TYPE,
    MARKET_CODE,
    STOCK_ID,
    WRITE_ROLE,
    HIDDEN,
    SORT_ORDER,
    CREATED_AT
)
SELECT
    'stocks/' ||
        CASE WHEN st.MARKET_CODE = 'KRX' THEN 'KR' ELSE 'US' END ||
        '/' || st.SYMBOL,
    st.STOCK_NAME || ' 게시판',
    st.SYMBOL || ' 종목 게시판',
    'STOCK',
    CASE WHEN st.MARKET_CODE = 'KRX' THEN 'KR' ELSE 'US' END,
    st.STOCK_ID,
    'USER',
    0,
    100,
    SYSTIMESTAMP
FROM STOCKS st
WHERE NOT EXISTS (
    SELECT 1
    FROM BOARDS b
    WHERE b.BOARD_TYPE = 'STOCK'
      AND b.STOCK_ID = st.STOCK_ID
);

UPDATE POSTS p
SET BOARD_ID = (
    SELECT b.BOARD_ID
    FROM BOARDS b
    JOIN STOCKS st ON st.STOCK_ID = b.STOCK_ID
    WHERE b.BOARD_TYPE = 'STOCK'
      AND st.SYMBOL = UPPER(p.SYMBOL)
      AND st.MARKET_CODE = CASE
            WHEN REGEXP_LIKE(p.SYMBOL, '^[0-9]{6}$') THEN 'KRX'
            ELSE 'NASDAQ'
      END
)
WHERE p.SYMBOL IS NOT NULL
  AND p.BOARD_ID IS NULL;

UPDATE POSTS p
SET BOARD_ID = (
    SELECT BOARD_ID
    FROM BOARDS
    WHERE BOARD_SLUG = 'free'
)
WHERE p.BOARD_ID IS NULL;

CREATE TABLE POST_RECOMMENDATIONS (
    POST_ID    NUMBER    NOT NULL,
    USER_ID    NUMBER    NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_POST_RECOMMENDATIONS_V2
        PRIMARY KEY (POST_ID, USER_ID),

    CONSTRAINT FK_POST_RECOMMENDS_POST_V2
        FOREIGN KEY (POST_ID)
        REFERENCES POSTS(POST_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_POST_RECOMMENDS_USER_V2
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(ID)
);

ALTER TABLE POSTS DROP COLUMN USERNAME;
ALTER TABLE POSTS DROP COLUMN SYMBOL;
ALTER TABLE COMMENTS DROP COLUMN USERNAME;

ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_BOARD_V2
    FOREIGN KEY (BOARD_ID)
    REFERENCES BOARDS(BOARD_ID);

COMMIT;
